### ISSUE TITLE
Blacklist and Mute not working + additional bug

### ISSUE THREAD

**Issue by Nesseley** [Rusketh/ComparableHoppers2#10]
1) Q: What is your name on spigot?
   A: Nesseley

2) Q: What is your Spigot build?
   A: 1.12.2

3) Q: What is your CH2 version?
   A: CH2 2.3.6 for MC 1.12.x

4) Q: Do you get any errors in console?
   A: No

5) Q: Have you read the full OP for the resource (https://www.spigotmc.org/resources/comparable-hoppers-2.45058/
   If not you should probably do so and double check you have set everything up correctly.
   A: Yes
   
6) Q: Please describe the issue you are having.
   A: Blacklist on hoppers dont work - lets every item trough. 
   B: Mute only shows the message "This upgrade requires another upgrade to be installed."
   C) Setting up a normal hopperline abow the Comparable hoppers doesnt make them use the whitelist. (https://gyazo.com/a5c35cea2fc3f41ba584be7b7e7521e3)

7) Q: Please describe how to replicate the issue, being as specific as possible.
   A: APlave a normal hopper above a hopper that is sorting items. It will let every item trough.
   
8) Q: Anything else you think we should know about your issue?
    A: Let me know if you need more info :)

**Comment by Rusketh** [comment]
A) A white list (added by comparable upgrade) will only allow items on the list though the hopper, where as a black list (added by comparable + black listing upgrade) will not allow items on that list though, all other items are white listed.

B) Mute upgrades are useless as they simply remove the particle effects from a hopper containing a comparable upgrade. Just an option for people who wish to do that, how ever installing it will require the comparable. upgrade since those are the only hoppers that currently have particles.

C) this one actually is a bug, its the speed upgrades that are ignoring the white list. I will fix this in the next version of Comparable Hoppers.

**Comment by Nesseley** [comment]
On the A) I dont get the blacklist to work at all, if I add Redstone to a blacklist-filter the redstone still goes trough.

Thanks for fixing the C) tho :D

**Comment by Rusketh** [comment]
A comparable upgrade will only allow the items on the white list to be pulled into the hopper.
A black list upgrade will not allow items on the black list to be pulled by a hopper.

White list = items that its allowed to.
Black list = Items its not allowed to.

**Comment by Nesseley** [comment]
I know this. Il add some videos to help you out :)
Video of mute upgrade still showing particles: https://youtu.be/8iKoEe7v8bI
Blacklist not working: https://youtu.be/D2UlI97tCUQ

**Comment by Rusketh** [comment]
In the first video you never actually installed the upgrade, due to the awfulness of the default hoppers bounding boxes you might need to adjust your position. You will know if it has installed because a message will tell you.

The second video is private and can not be viewed with out a google apps account.

**Comment by Rusketh** [comment]
In the second video your white list and black lists inventory title where both Filter. Is this deliberately set up in configs or should these 2 titles differ?

**Comment by Nesseley** [comment]
I have not changed blacklisting name at all, maybe the whitelist overrwights the blacklist somehow? Il do some testing when I have the time and come back to you

**Comment by Nesseley** [comment]
I made a clean install of CH2.
Blacklist is still not working. Let me know if im doing something wrong
https://youtu.be/yYUlTZr0bdU

Also, I can't install the mute-upgrade ona comparable hopper by shift + rightclicking (also tried shift + leftclick not working)

**Comment by Rusketh** [comment]
A fix has been released.
