### ISSUE TITLE
Chunk loading issue

### ISSUE THREAD

**Issue by airoons** [Rusketh/ComparableHoppers2#14]
_For some reason, my previous issue wasn't sent correctly._

1) Q: What is your name on spigot?
   A: TheIronMinerLv

2) Q: What is your Spigot build?
   A: PaperSpigot 1.8.8

3) Q: What is your CH2 version?
   E.G CH 2.3.1 for MC 1.12.x
   A: CH 2.3.7

4) Q: Do you get any errors in console?
   A: No errors

5) Q: Have you read the full OP for the resource (https://www.spigotmc.org/resources/comparable-hoppers-2.45058/
   A: Yes
   
6) Q: Please describe the issue you are having.
   A: I have a ChunkLoader system on my server and it doesn't work with ComparableHoppers. Basically, I use Citizens to create NPC's that loads only chunk they are in. This works with things like spawners and stuff, but hoppers just don't work, even if the NPC is near the hoppers themselves.

7) Q: Please describe how to replicate the issue, being as specific as possible.
   A: Create a NPC, enable "chunk loading", and "remove-from-list: false". Then just leave the chunk so hoppers would work themselves in the chunk with the NPC beside them.
   
8) Q: Anything else you think we should know about your issue?
    A: Fix if possible!

**Comment by Rusketh** [comment]
Comparable hoppers use the vanilla chunk loading mechanics and events from spigot to manage witch comparable hoppers are comparable. This also manages witch hoppers can push/pull etc.

I really don't want to be integrating support for 3rd party plugins, especially when the the plugin author can call spigots events, witch would then trigger CH2 to update this.

I am going to close this ticket on the grounds that 1.8.8 itself will no longer be supported on newer builds of the plugin. This is because 1.12 and 1.8 are too different and most of the features planned will not be possible in 1.8.8 spigot.

Drop us the name of your chunk loader over Discord and I will take a look to see how much work would be needed to support this.

**Comment by airoons** [comment]
I've created ChunkLoader plugin myself, that as I mentioned just spawns CITIZENS plugin NPC's. I don't ask to support my plugin or whatnot, I'm asking for a fix that hoppers needs a real player nearby to work.

**Comment by Rusketh** [comment]
This would have to be done in your plugin.
In CH2 when **ChunkLoadEvent** is called CH" will check every tile entity in that chunk for an upgraded hopper, for each on found it is added onto a array.

In the same way when **ChunkUnloadEvent** is called CH2 will remove all those entries of the array.

Only the hoppers stored on the array will actually push/pull items. Any CH2 upgraded hopper that is not in this array will literally do nothing not even vanilla mechanics.

**Comment by Rusketh** [comment]
Update, this might be something i can fix after all.

Seems i'm not ignoring events that have been canceled, ill release this as a quick patch later.

**Comment by airoons** [comment]
The thing is - chunk isn't unloaded at any point or whatsoever - the NPC keeps chunk loaded, even if every player in the server lefts - one chunk with that npc is kept loaded, so yeah - this needs to be fixed imo

**Comment by Rusketh** [comment]
As long as you are cancelling the ChunkUnloadEvent for your chunk loader chunks then 2.3.8 should work for you. 

P.S Creating a fake player is not the way to make a chunk loader.
